services:
  # Backend API Service
  - type: web
    name: lms-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://ojterry339:ojterry@cluster0.rzqbn1p.mongodb.net/lms?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          type: web
          name: lms-frontend
          property: url

  # Frontend React Service
  - type: web
    name: lms-frontend
    env: static
    plan: free
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: lms-backend
          property: url
